server {
    listen 80;
    server_name lackeys.ceee.cloud;
    access_log /var/log/nginx/cumora-pilot-access.log;
    error_log /var/log/nginx/cumora-pilot-error.log;
    location ^~ /.well-known/acme-challenge/ {
        root /home/cee/apps/cumora-pilot/acme;
    }
    location / { return 503; }
}
